# stages:
#   - master
#   - stop
#   - server

# prd_master:
#   stage: master
#   tags:
#     - master
#   only:
#     - master
#   script:
#     - xcopy .\. D:\vue-screen\server /e/y
#     - cd /d D:\vue-screen\server
#     - npm i
#   after_script:
#     - dir

# prd_stop:
#   stage: stop
#   tags:
#     - master
#   only:
#     - master
#   script:
#     - cd /d D:\vue-screen\server
#     - pm2.cmd stop screen
#     # - npm run stop
#   allow_failure: true

# prd_server:
#   stage: server
#   tags:
#     - master
#   only:
#     - master
#   script:
#     - cd /d D:\vue-screen\server
#     - pm2.cmd start screen
#     # - npm run pm2
#   after_script:
#     - pm2.cmd list
